apiVersion: v1
kind: Service
metadata:
  name: {{ include "spire.fullname" . }}-server
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "spire.server.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: grpc
      port: {{ .Values.service.port }}
      targetPort: grpc
      protocol: TCP
  selector:
    {{- include "spire.server.selectorLabels" . | nindent 4 }}
