apiVersion: v2
name: spire
description: A Helm chart for deploying spire-server and spire-agent.
type: application
version: 0.2.0
appVersion: "0.12.3"
keywords: ["spiffe", "spire", "spire-server", "spire-agent"]
home: https://github.com/philips-labs/helm-charts/charts/spire
sources:
  - https://github.com/philips-labs/helm-charts/charts/spire
maintainers:
  - name: marcofranssen
    email: marco.franssen@philips.com
    url: https://marcofranssen.nl
kubeVersion: ">=1.19.0-0"
