name: Continuous Integration

on:
  push:
    paths:
      - 'charts/**'
  pull_request:
    paths:
      - 'charts/**'

jobs:
  lint-chart:
    runs-on: ubuntu-20.04
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.5.0

      - name: Set up Python
        uses: actions/setup-python@v2.2.1
        with:
          python-version: 3.7

      - name: Setup chart-testing
        uses: helm/chart-testing-action@v2.0.1
        with:
          version: v3.3.1

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed --target-branch main)
          if [[ -n "$changed" ]]; then
            echo "::set-output name=changed::true"
          fi

      - name: Run chart-testing (lint)
        run: |
          ct lint --debug \
            --target-branch main \
            --chart-repos philips-labs=https://philips-labs.github.io/helm-charts/

      - name: Run helm-docs
        run: .github/helm-docs.sh

    outputs:
      changed: ${{ steps.list-changed.outputs.changed }}

  kubeval-chart:
    runs-on: ubuntu-20.04
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    needs:
      - lint-chart
    strategy:
      matrix:
        k8s:
          - v1.15.7
          - v1.16.4
          - v1.17.4
          - v1.18.1
          - v1.19.3
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Run kubeval
        env:
          KUBERNETES_VERSION: ${{ matrix.k8s }}
        run: .github/kubeval.sh
